[project]
id = "std"
name = "Mach Standard Library"
version = "0.4.0"
dir_src = "src"
dir_out = "out"
dir_dep = "dep"
target = "native"

[targets.linux]
os = "linux"
isa = "x86_64"
abi = "sysv64"
mode = "library"
entrypoint = "lib.mach"
artifacts = "linux"
dir_tests = "tests"
binary = "linux/bin/libmachstd.a"
