[project]
id      = "std"
name    = "Mach Standard Library"
version = "0.5.0"
src     = "src"
dep     = "dep"
target  = "native"
out     = "out/{target}/{profile}/bin/{name}{ext}"
obj     = "out/{target}/{profile}/obj"
ir      = "out/{target}/{profile}/ir"
asm     = "out/{target}/{profile}/asm"
tests   = "out/{target}/{profile}/test/{name}"

[target.linux]
isa = "x86_64"
os  = "linux"
abi = "sysv64"

[os.windows]
libs = ["kernel32.dll"]

[lib.std]
entry = "lib.mach"
kind  = "static"
